import "./globals.css";
import NavBar from "./navBar";

export const metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({ children }) {
    return (
        <html lang="en">
            <body>
                <div className="wrapper">
                    {/* <div className="blurText"></div> */}
                    <div className="blurText"></div>
                    <NavBar></NavBar>
                </div>
                <div className="htmlTopMargin"></div>
                {children}
            </body>
        </html>
    );
}

function NavBarIcon({ link, func }) {
    return (
        <a className="navBarIcon" href={link}>
            {func}
        </a>
    );
}
